[
  {"Jodoh tuhan yang atur, kalo kamu masi jomblo berati anda susah diatur"},
  {"Jangan berharap lebih pada manusia"},
  {"Memaafkan belum tentu membuat kita lebih baik atau bahkan merasa lebih baik, tetapi yang jelas membuka jalan kebaikan."},
  {"Rahasia dari kesuksesan kita adalah bahwa kita tidak pernah menyerah."},
  {"Kesuksesan dan kegagalan adalah sama-sama bagian dalam hidup. Keduanya hanyalah sementara."},
  {"Belajarlah rendah hati, rendahkan hatimu serendah-rendahnya hingga tidak ada seorangpun yang bisa merendahkanmu."},
  {"Yang keren itu bukan anak muda yang banyak gaya, tapi anak muda yang banyak karya."},
  {"Jangan biarkan opini orang lain menenggelamkan suara dari dalam diri Anda."}
  {"Jika rencana Anda tidak berjalan, maka ganti rencana tersebut, jangan tujuannya."},
  {"Hidup tak selamanya tentang pacar."},
  {"Kesepian terburuk adalah tidak nyaman dengan diri sendiri."},
  {"Secapek-capeknya kerja lebih capek nganggur."},
  {"Balas dendam terbaik adalah menjadikan dirimu lebih baik."},
  {"Pekerjaan yang paling tak kunjung bisa diselesaikan adalah pekerjaan yang tak kunjung pernah dimulai."},
  { "Bukan bahagia yang menjadikan kita bersyukur, tetapi dengan bersyukurlah yang akan menjadikan hidup kita bahagia."},
  {"Mulai setiap harimu dengan pikiran positif dan hati yang bersyukur."},
  {"Jadilah pribadi yang menantang masa depan, bukan pengecut yang aman di zona nyaman."},
  {"Perjuangan merupakan tanda perjalananmu menuju sukses."},
  {"Cinta bukanlah bertahan seberapa lama. Tetapi seberapa jelas dan ke arah mana."},
  {"Janganlah pernah menyerah ketika Anda masih mampu berusaha lagi. Tidak ada kata berakhir sampai Anda berhenti mencoba." },
  {"Seorang pemenang adalah pemimpi yang tidak pernah menyerah."},
  {"Optimisme adalah iman yang menuntun Anda ke pencapaian."},
  {"Jangan membandingkan diri Anda dengan orang lain. Bandingkan diri Anda dengan pribadi yang kemarin.”}
  {"Hal-hal besar tidak pernah datang dari zona nyaman."},
  {"Sakit dalam perjuangan itu hanya sementara. Bisa jadi kamu rasakan dalam semenit, sejam, sehari, atau setahun. Namun jika menyerah, rasa sakit itu akan terasa selamanya."},
  {"Hidup tak semudah membalikkan telapak tangan, tetapi dengan telapak tangan kita dapat mengubah hidup kita jauh lebih baik lagi."},
  {"Hanya seseorang yang takut yang bisa bertindak berani. Tanpa rasa takut itu tidak ada apapun yang bisa disebut berani."},
  {"Siapapun yang berusaha menjatuhkanmu memang sudah berada di bawahmu."},
  {"Membuang waktumu untuk melakukan hal yang tidak berguna dapat menghancurkan masa depanmu."},
  {"Kegagalan itu penting karena tanpa kegagalan, tidak ada penghargaan untuk keberhasilan."},
  {"Walau terlihat sulit, kalau tidak dicoba tidak akan pernah tahu bagaimana cara menaklukkannya."},
  {"Dalam perkataan, tidak ada salahnya merendahkan diri, namun dalam aktivitas tunjukkanlah kemampuanmu."}
]